apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingus-api-deployment
  labels:
    app: ratingus-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-ratingus-api
  template:
    metadata:
      labels:
        app: http-ratingus-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ratingus-api
          image: registry.purplecode.ru/purplecode/ratingus/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-url
                  key: DATABASE_URL
            - name: REFRESH_TOKEN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: REFRESH_TOKEN_JWT_SECRET
            - name: ACCESS_TOKEN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: ACCESS_TOKEN_JWT_SECRET
            - name: ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: access-id
                  key: ACCESS_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: bucket-name
                  key: BUCKET_NAME
            - name: RUSENDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rusender-api-key
                  key: RUSENDER_API_KEY
          resources:
            limits:
              memory: "500Mi"
            requests:
              cpu: "0.05"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ratingus-service
spec:
  selector:
    app: http-ratingus-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  type: ClusterIP